### ISSUE TITLE
Glob **/!(*-dbg).@(js) is wrongly translated into RegExp and thus DOES match -dbg.js files

### ISSUE THREAD

**Issue by kristian** [micromatch/picomatch#93] opened 2021-08-26 09:28 UTC
The Glob:

```
**/!(*-dbg).@(js)
```

Which should match any `.js` files that do not end with `-dbg` is wrongly translated to:

```
^(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.{1,2}(?:[\\/]|$)).)*?)[\\/])(?:(?!(?:[^\\/]*?-dbg).@(js))[^\\/]*?)\.(js))$
```

Please note how for the negative backreference, the glob pattern `.@(js)` is literally taking into the regex and is not translated into a regexp / excapted itself? Expected RegExp would have been:

```
^(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.{1,2}(?:[\\/]|$)).)*?)[\\/])(?:(?!(?:[^\\/]*?-dbg)\.(js))[^\\/]*?)\.(js))$
```

**Comment by mrmlnc** [comment] 2021-10-31 14:46
The bug related to https://github.com/micromatch/picomatch/pull/84.

Similar patterns that lead to false behavior:

```
!(*.d).{ts,tsx} → match 'file.d.ts'
```

**Comment by mrmlnc** [comment] 2022-01-02 15:01
I did a little research on this problem. The problem is in [this block](https://github.com/micromatch/picomatch/blob/719d348d8a01cf23c6c10568191c1ad5a3fc33e3/lib/parse.js#L252-L254). Here we get everything after the closing parenthesis and put it in the pattern. This is an error because any other nested expression can come after the closing parenthesis.

Unfortunately, I'm not sure that this problem can be fixed without rewriting most of this module. Literally, we need to stop and parse the following expression after the parenthesis and then go to back and insert the result.

**Comment by jonschlinkert** [comment] 2022-01-02 15:26
@mrmlnc nice work on debugging and figuring out where the problem is!  

> Unfortunately, I'm not sure that this problem can be fixed without rewriting most of this module.

It should be possible without having to refactor to use an AST. FWIW, I create multiple versions of this with an AST first, but all approaches were slower due to object allocation etc. But I'm open to switching back to the AST, or maybe just pushing a version with an AST up to a branch. 

Before that, I have an idea of how to do this without much code. @mrmlnc what are your thoughts on what the resulting regex should be to make this work?

**Comment by mrmlnc** [comment] 2022-01-02 15:43
Heh, I can make this work by calling the `parse` function on the rest of string.

```diff
if (token.inner.includes('*') && (rest = remaining()) && /^\.[^\\/.]+$/.test(rest)) {
+  // Disabling the `fastpaths` option due to a problem with parsing strings as `.ts` in the pattern like `**/!(*.d).ts`.
+  const value = parse(rest, { ...options, fastpaths: false }).tokens
+    .map(token => token.output || token.value)
+    .join('');

-  output = token.close = `)${rest})${extglobStar})`;
+  output = token.close = `)${value})${extglobStar})`;
}
```

It passes all the tests, including the ones I added.

Previous regexp:

```js
// !(*.d).{ts,tsx}
/^(?:(?=.)(?:(?!(?:[^/]*?\.d).{ts,tsx})[^/]*?)\.(ts|tsx))$/
                              ^----------- wrong output
```

The current regexp:

```js
// !(*.d).{ts,tsx}
/^(?:(?=.)(?:(?!(?:[^/]*?\.d)\.(ts|tsx))[^/]*?)\.(ts|tsx))$/
                               ^----------- correct output
```

But it doesn't work for the original pattern from this issue.

@jonschlinkert, if the suggested solution (calling the `parse` function) suits you, then I can finish it and submit PR.

**Comment by jonschlinkert** [comment] 2022-01-02 15:52
> if the suggested solution (calling the `parse` function) suits you, then I can finish it and submit PR.

Yes that's great!  was just doing something much more complicated, your solution is better. Thanks and nice work!

**Comment by mrmlnc** [comment] 2022-01-02 17:15
Fixed by #102 and will be released soon under version `2.3.1`.

**Closed by mrmlnc** 2022-01-02 17:15 UTC
Labels: bug

**Comment by kristian** [comment] 2022-01-02 17:33
Thanks @mrmlnc and @jonschlinkert! One workaround less in our code! Highly appreciated! 👍

**Comment by jonschlinkert** [comment] 2022-01-02 17:43
@kristian thank you for creating the issue and for the great description to help us get this figured out!

**Comment by Jock0707** [comment] 2022-12-19 21:50
Thanks for the help
